name: orav
author: FREE2WIN
version: 1.0
main: de.logilutions.orav.OravPlugin
api-version: 1.17
commands:
  leakcoords:
    description: Leaks the specified players current coordinates into discord an ingame chat
    usage: /leakcoords <player>
  orav:
    description: An Admin Command for orav admins
    usage: /orav admin